### ISSUE TITLE
Get flutter version failed in `.husky/pre-commit` of git submodule

### ISSUE THREAD

**Issue by thomasnti** [hyiso/husky#4] opened 2023-04-10 08:59 UTC
**The error i get**

The current Flutter SDK version is 0.0.0-unknown.

Because soft1_core requires Flutter SDK version >=1.17.0, version solving failed.
pub get failed

**Comment by hyiso** [comment] 2023-04-10 09:13
This seems to be the version conflict between your local Flutter SDK version(here 0.0.0-unknown) and package `soft1_core` requreid Flutter SDK version(>= 1.7.0)

**Comment by thomasnti** [comment] 2023-04-10 09:35
Why my flutter version is 0.0.0-unknown and when I run flutter --version I get :

Flutter 3.7.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4b12645012 (6 days ago) • 2023-04-03 17:46:48 -0700
Engine • revision ec975089ac
Tools • Dart 2.19.6 • DevTools 2.20.1

**Comment by hyiso** [comment] 2023-04-10 09:39
Could you provide a minimum code sample and the commands you used to reproduce this error?

**Comment by thomasnti** [comment] 2023-04-10 11:29
I came to the conclusion that this happens when I put a flutter package as a submodule into a project. Then, when I cd into package's folder and run git commit command I get this error.

**Comment by hyiso** [comment] 2023-04-10 11:58
Where did you run `husky install`, what is the content of the running git hook,  and whether there are different Flutter SDKs in you environment?

What happened if you just run the script in your git hook?

**Comment by hyiso** [comment] 2023-04-10 12:03
A minimum reproducible code sample could be more helpful to find what caused the problem.

**Comment by thomasnti** [comment] 2023-04-11 07:15
I made an example in order to reproduce this issue. You can clone this repository https://github.com/thomasnti/husky-issue-app and then run starter.sh.
If you cd into packages/husky_issue_package and then make a commit you will reproduce it (you must comment out flutter --version in pre-commit)

**Comment by hyiso** [comment] 2023-04-11 07:23
Thanks for the code example, I'll  test it later today.

**Comment by hyiso** [comment] 2023-04-11 15:53
Have reproduced this locally.

Run `.husky/pre-commit` directly passed, but failed when called by git hook.

Tested running `flutter pub get -v` directly and by git hook `.husky/pre-commit`, found following difference:

When running directly:
```
Building flutter tool...
[  +15 ms] executing: sysctl hw.optional.arm64
[  +13 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +1 ms] executing: [/Users/xxxxx/.fvm/versions/3.7.10/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +22 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 4b12645012342076800eb701bcdfe18f87da21cf
[        ] executing: [/Users/xxxxx/.fvm/versions/3.7.10/] git tag --points-at
4b12645012342076800eb701bcdfe18f87da21cf
[  +33 ms] Exit code 0 from: git tag --points-at 4b12645012342076800eb701bcdfe18f87da21cf
[        ] 3.7.10
[   +9 ms] executing: [/Users/xxxxx/.fvm/versions/3.7.10/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/Users/xxxxx/.fvm/versions/3.7.10/] git ls-remote --get-url origin
[  +18 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +31 ms] executing: [/Users/xxxxx/.fvm/versions/3.7.10/] git rev-parse --abbrev-ref HEAD
[  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
```
And called by git hook:
```
Building flutter tool...
[  +15 ms] executing: sysctl hw.optional.arm64
[  +12 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +1 ms] executing: [/Users/xxxxx/.fvm/versions/3.7.10/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +11 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 00ecff8bcfeb248e63a9cecf24dd9e58ba2492ff
[        ] executing: [/Users/xxxxx/.fvm/versions/3.7.10/] git tag --points-at
00ecff8bcfeb248e63a9cecf24dd9e58ba2492ff
[  +38 ms] Exit code 0 from: git tag --points-at 00ecff8bcfeb248e63a9cecf24dd9e58ba2492ff
[   +2 ms] executing: [/Users/xxxxx/.fvm/versions/3.7.10/] git describe --match *.*.* --long --tags
00ecff8bcfeb248e63a9cecf24dd9e58ba2492ff
[  +42 ms] Exit code 128 from: git describe --match *.*.* --long --tags 00ecff8bcfeb248e63a9cecf24dd9e58ba2492ff
[        ] fatal: No tags can describe '00ecff8bcfeb248e63a9cecf24dd9e58ba2492ff'.
           Try --always, or create some tags.
[   +2 ms] Could not interpret results of "git describe":
[   +7 ms] executing: [/Users/xxxxx/.fvm/versions/3.7.10/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +8 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] fatal: HEAD does not point to a branch
[   +3 ms] executing: [/Users/xxxxx/.fvm/versions/3.7.10/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
```

Here we can see the different log hash `4b12645012342076800eb701bcdfe18f87da21cf` vs `00ecff8bcfeb248e63a9cecf24dd9e58ba2492ff` returned by command `git -c log.showSignature=false log -n 1
--pretty=format:%H`

The commit hash `4b12645012342076800eb701bcdfe18f87da21cf` is last log of Flutter SDK 3.7.10, but `00ecff8bcfeb248e63a9cecf24dd9e58ba2492ff` is the last one of package `husky_issue_package`.

Today just paused here, I'll continue tomorrow.

**Comment by hyiso** [comment] 2023-04-12 14:06
@thomasnti This seems to be a bug of Flutter (executed in hook of git submodule), not a problem of `husky`.

You can try following steps:
1. `dart run husky uninstall` under `husky_issue_package` to uninstall husky.
2. Remove `.husky/` directory under `husky_issue_package`
3. Add `husky-issue-app/.git/modules/packages/husky_issue_package/hooks/pre-commit` hook with following content
```
#!/usr/bin/env sh

flutter pub get -v
```
  and make it executable.

4. Make a commit under package `husky_issue_package`

`flutter pub get -v` will fail.

**Comment by hyiso** [comment] 2023-04-12 15:07
Report a issue: https://github.com/flutter/flutter/issues/124681

**Comment by thomasnti** [comment] 2023-04-13 06:45
Thanks a lot for the help @hyiso 😊

**Comment by hyiso** [comment] 2023-04-13 07:40
Closing as not related to `husky`

**Closed as completed by hyiso** 2023-04-13 07:40 UTC

**Comment by dodatw** [comment] 2024-11-16 05:48
Hi everyone, after a year, Did you find any workaround for this issue.
